### ISSUE TITLE
How run it on Windows

### ISSUE THREAD

**Issue by mehranexpert** [yashk2810/Keylogger#1]
How run it under windows ?

**Comment by yashk2810** [comment]
Use eclipse or any other IDE to create an executable file of 'keylogger.cpp' and then just click on the executable file. It will start running and will log the keys in the file specified. The program will also hide itself. So to check whether its running or not, open the task manager and look for the executable there.

If you don't want to create the executable file just run it as you normally run a c++ program.

**Comment by mehranexpert** [comment]
Ok , its seems not Capture some key Like : [] ;' >? .< 

why ?

**Comment by yashk2810** [comment]
Because i haven't written conditions for them. If you want, you can write it. Google virtual keys and then add them in the code.
